[build-system]
requires = ["setuptools>=69.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py312"

[tool.pytest.ini_options]
addopts = "--cov=course_ml_streamlit"
testpaths = [
    "tests",
]
filterwarnings = "ignore::DeprecationWarning:dateutil.*:"
